//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace PiIDE.Options.Editor.SyntaxHighlighter {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class SyntaxHighlighterSettings : ApplicationSettingsBase {
        
        private static SyntaxHighlighterSettings defaultInstance = ((SyntaxHighlighterSettings)(Synchronized(new SyntaxHighlighterSettings())));
        
        public static SyntaxHighlighterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool HighlightJediNames {
            get {
                return ((bool)(this["HighlightJediNames"]));
            }
            set {
                this["HighlightJediNames"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool HighlightKeywords {
            get {
                return ((bool)(this["HighlightKeywords"]));
            }
            set {
                this["HighlightKeywords"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool HighlightBrackets {
            get {
                return ((bool)(this["HighlightBrackets"]));
            }
            set {
                this["HighlightBrackets"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool HighlightIndentation {
            get {
                return ((bool)(this["HighlightIndentation"]));
            }
            set {
                this["HighlightIndentation"] = value;
            }
        }
    }
}
