//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace PiIDE {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class GlobalSettings : ApplicationSettingsBase {
        
        private static GlobalSettings defaultInstance = ((GlobalSettings)(Synchronized(new GlobalSettings())));
        
        public static GlobalSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Cascadia Code")]
        public string TextEditorFontFamily {
            get {
                return ((string)(this["TextEditorFontFamily"]));
            }
            set {
                this["TextEditorFontFamily"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("14")]
        public int TextEditorFontSize {
            get {
                return ((int)(this["TextEditorFontSize"]));
            }
            set {
                this["TextEditorFontSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public int SelectedCOMPort {
            get {
                return ((int)(this["SelectedCOMPort"]));
            }
            set {
                this["SelectedCOMPort"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PylintIsUsable {
            get {
                return ((bool)(this["PylintIsUsable"]));
            }
            set {
                this["PylintIsUsable"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool JediIsUsable {
            get {
                return ((bool)(this["JediIsUsable"]));
            }
            set {
                this["JediIsUsable"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PythonIsInstalled {
            get {
                return ((bool)(this["PythonIsInstalled"]));
            }
            set {
                this["PythonIsInstalled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AmpyIsUsable {
            get {
                return ((bool)(this["AmpyIsUsable"]));
            }
            set {
                this["AmpyIsUsable"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public List<String> LastOpenedLocalFolderPaths {
            get {
                return ((List<String>)(this["LastOpenedLocalFolderPaths"]));
            }
            set {
                this["LastOpenedLocalFolderPaths"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public List<String> LastOpenedLocalFilePaths {
            get {
                return ((List<String>)(this["LastOpenedLocalFilePaths"]));
            }
            set {
                this["LastOpenedLocalFilePaths"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public List<String> LastOpenedBoardFilePaths {
            get {
                return ((List<String>)(this["LastOpenedBoardFilePaths"]));
            }
            set {
                this["LastOpenedBoardFilePaths"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string LastOpenedFilePath {
            get {
                return ((string)(this["LastOpenedFilePath"]));
            }
            set {
                this["LastOpenedFilePath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("BoardFiles/")]
        public string LocalBoardFilesPath {
            get {
                return ((string)(this["LocalBoardFilesPath"]));
            }
            set {
                this["LocalBoardFilesPath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int CompletionsMode {
            get {
                return ((int)(this["CompletionsMode"]));
            }
            set {
                this["CompletionsMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool BlackIsUsable {
            get {
                return ((bool)(this["BlackIsUsable"]));
            }
            set {
                this["BlackIsUsable"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
    }
}
